site_name: matheuscruz.dev
repo_url: https://github.com/mcruzdev/blog
site_url: https://mcruzdev.github.io/
theme:
  name: material
  icon:
    logo: material/keyboard
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
plugins: 
  - search
  - social:
      cards_layout: default/accent
  - blog:
      post_excerpt: required
      blog_toc: true
      blog_dir: .
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mcruzdev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mcruzdev1
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mcruzdev1

copyright: |
  &copy; 2024 <a href="https://github.com/mcruzdev"  target="_blank" rel="noopener">Matheus Cruz</a>