site_name: matheuscruz.dev

theme:
  features:
    - content.code.copy
  name: material
plugins: 
  - search
  - info
  - blog:
      blog_dir: .
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences