name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install mkdocs-rss-plugin
      - run: mkdocs gh-deploy --force
      - run: mkdocs build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_access_key: "${{ secrets.AWS_SECRET_KEY }}"
          aws_bucket: "${{ secrets.AWS_BUCKET }}"
          source_dir: site
          destination_dir: ""
